name: nf-core AWS full size tests
# This workflow is triggered on published releases.
# It can be additionally triggered manually with GitHub actions workflow dispatch button.
# It runs the -profile 'test_full' on AWS batch

on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  run-tower:
    name: Run AWS AlphaFold2 full monomer tests
    if: github.repository == 'nf-core/proteinfold'
    runs-on: ubuntu-latest
    # Do a full-scale run on each of the mode
    strategy:
      matrix:
        mode:
          [
            "_alphafold2_standard",
            "_alphafold2_split",
            "_alphafold2_multimer",
            "_colabfold_local",
            "_colabfold_webserver",
            "_colabfold_multimer",
            "_esmfold",
            "_esmfold_multimer",
          ]
    steps:
      - name: Launch workflow via tower
        uses: seqeralabs/action-tower-launch@v2
        with:
          workspace_id: ${{ secrets.TOWER_WORKSPACE_ID }}
          access_token: ${{ secrets.TOWER_ACCESS_TOKEN }}
          compute_env: ${{ secrets.TOWER_COMPUTE_ENV }}
          revision: ${{ github.sha }}
          workdir: s3://${{ secrets.AWS_S3_BUCKET }}/work/proteinfold/work-${{ github.sha }}
          parameters: |
            {
              "hook_url": "${{ secrets.MEGATESTS_ALERTS_SLACK_HOOK_URL }}",
              "outdir": "s3://${{ secrets.AWS_S3_BUCKET }}/proteinfold/results-${{ github.sha }}/mode_${{ matrix.mode }}"
            }
          profiles: test_full_${{ matrix.mode }},aws_tower
      - uses: actions/upload-artifact@v3
        with:
          name: Tower debug log file
          path: |
            tower_action_*.log
            tower_action_*.json
